version: "3.7"

services:
  # Proxy reverso (Nginx)
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      nginx-app_app_network:
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
      - app3

  # Aplicação 1
  app1:
    build: ./app/app1
    container_name: app1
    networks:
      nginx-app_app_network:
    expose:
      - "80"

  # Banco de dados 1 (MySQL) com PHPMyAdmin
  db1:
    image: mysql:5.7
    container_name: db1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app1_db
    volumes:
      - db1_data:/var/lib/mysql
    networks:
      nginx-app_db1_network:

  db1_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: db1_phpmyadmin
    environment:
      PMA_HOST: db1
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    networks:
      - nginx-app_db1_network # Nome correto da rede
    ports:
      - "8081:80"

  # Container de avaliação para app1
  jadilsonpaiva_full_app1:
    image: jadilsonpaiva/full
    container_name: jadilsonpaiva_full_app1
    networks:
      - nginx-app_db1_network

  # Aplicação 2
  app2:
    build: ./app/app2
    container_name: app2
    networks:
      nginx-app_app_network:

  # Banco de dados 2 (MySQL) com PHPMyAdmin
  db2:
    image: mysql:5.7
    container_name: db2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app2_db
    volumes:
      - db2_data:/var/lib/mysql
    networks:
      nginx-app_db2_network:

  db2_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: db2_phpmyadmin
    environment:
      PMA_HOST: db2
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    networks:
      - nginx-app_db2_network # Nome correto da rede
    ports:
      - "8082:80"

  # Container de avaliação para app2
  jadilsonpaiva_full_app2:
    image: jadilsonpaiva/full
    container_name: jadilsonpaiva_full_app2
    networks:
      - nginx-app_db2_network

  # Aplicação 3
  app3:
    build: ./app/app3
    container_name: app3
    networks:
      nginx-app_app_network:

  # Banco de dados 3 (MySQL) com PHPMyAdmin
  db3:
    image: mysql:5.7
    container_name: db3
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app3_db
    volumes:
      - db3_data:/var/lib/mysql
    networks:
      - nginx-app_db3_network

  db3_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: db3_phpmyadmin
    environment:
      PMA_HOST: db3
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    networks:
      nginx-app_db3_network:
    ports:
      - "8083:80"

  # Container de avaliação para app3
  jadilsonpaiva_full_app3:
    image: jadilsonpaiva/full
    container_name: jadilsonpaiva_full_app3
    networks:
      - nginx-app_db3_network

volumes:
  db1_data:
  db2_data:
  db3_data:

networks:
  nginx-app_db1_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.10.0/28 # Faixa de IP modificada para evitar sobreposição
  nginx-app_db2_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.10.16/28 # Faixa de IP modificada para evitar sobreposição
  nginx-app_db3_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.10.32/28 # Faixa de IP modificada para evitar sobreposição
  nginx-app_app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.10.48/28 # Faixa de IP modificada para evitar sobreposição
