version: '3.7'

services:
  # Proxy reverso (Nginx)
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      app_network:
        ipv4_address: 10.10.10.2
    ports:
      - "81:81"
    depends_on:
      - app1
      - app2
      - app3

  # Aplicação 1
  app1:
    build: ./app/app1
    container_name: app1
    networks:
      app_network:
        ipv4_address: 10.10.10.3

  # Banco de dados 1 (MySQL) com PHPMyAdmin
  db1:
    image: mysql:5.7
    container_name: db1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app1_db
    volumes:
      - db1_data:/var/lib/mysql
    networks:
      app_network:
        ipv4_address: 10.10.10.4

  db1_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: db1_phpmyadmin
    environment:
      PMA_HOST: db1
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      app_network:
        ipv4_address: 10.10.10.5

  # Aplicação 2
  app2:
    build: ./app/app2
    container_name: app2
    networks:
      app_network:
        ipv4_address: 10.10.10.6

  # Banco de dados 2 (MySQL) com PHPMyAdmin
  db2:
    image: mysql:5.7
    container_name: db2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app2_db
    volumes:
      - db2_data:/var/lib/mysql
    networks:
      app_network:
        ipv4_address: 10.10.10.7

  db2_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: db2_phpmyadmin
    environment:
      PMA_HOST: db2
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8082:80"
    networks:
      app_network:
        ipv4_address: 10.10.10.8

  # Aplicação 3
  app3:
    build: ./app/app3
    container_name: app3
    networks:
      app_network:
        ipv4_address: 10.10.10.9

  # Banco de dados 3 (MySQL) com PHPMyAdmin
  db3:
    image: mysql:5.7
    container_name: db3
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app3_db
    volumes:
      - db3_data:/var/lib/mysql
    networks:
      app_network:
        ipv4_address: 10.10.10.10

  db3_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: db3_phpmyadmin
    environment:
      PMA_HOST: db3
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8083:80"
    networks:
      app_network:
        ipv4_address: 10.10.10.11

  # Contêiner de avaliação
  jadilsonpaiva_full:
    image: jadilsonpaiva/full
    container_name: jadilsonpaiva_full
    networks:
      app_network:
        ipv4_address: 10.10.10.12

volumes:
  db1_data:
  db2_data:
  db3_data:

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.10.0/24"
