version: '3.9'

networks:
  private_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24

services:
  proxy:
    image: nginx:latest
    container_name: proxy
    volumes:
    - ./certs/app1.local.crt:/etc/ssl/certs/app1.local.crt
    - ./certs/app1.local.key:/etc/ssl/private/app1.local.key
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "445:443"
      - "8080:80"
    networks:
      private_network:
        ipv4_address: 10.10.10.2
    depends_on:
      - app1
      - app2
      - app3

  app1:
    build:
      context: ./firstApp
    container_name: app1
    networks:
      private_network:
        ipv4_address: 10.10.10.10
    environment:
      - DATABASE_URL=mysql://user:password@db1:3306/app1db
    depends_on:
      - db1

  db1:
    image: mysql:8.0
    container_name: db1
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app1db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      private_network:
        ipv4_address: 10.10.10.11

  app2:
    build:
      context: ./secondApp
    container_name: app2
    networks:
      private_network:
        ipv4_address: 10.10.10.20
    environment:
      - DATABASE_URL=postgresql://user:password@db2:5432/app2db
    depends_on:
      - db2

  db2:
    image: postgres:15
    container_name: db2
    environment:
      POSTGRES_DB: app2db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      private_network:
        ipv4_address: 10.10.10.21

  app3:
    build:
      context: ./thirdApp
    container_name: app3
    networks:
      private_network:
        ipv4_address: 10.10.10.30
    environment:
      - DATABASE_URL=mongodb://db3:27017/app3db
    depends_on:
      - db3

  db3:
    image: mongo:6
    container_name: db3
    networks:
      private_network:
        ipv4_address: 10.10.10.31
